remote_theme: pages-themes/minimal@v0.2.0
title: Chris Huff's website
description: Working as intended.
url: https://chrisnhuff.github.io
baseurl: /
plugins:
  - jekyll-remote-theme
nav:
  - title: Home
    url: /
    title: About
    url: /about
    title: Blog
    url: /blog
