remote_theme: jekyll-theme-chirpy
title: Chris Huff's website
description: Working as intended.
url: https://chrisnhuff.github.io
baseurl: /
nav:
  - title: Home
    url: /
    title: About
    url: /about
    title: Blog
    url: /blog
