# Site Config
url: https://chrisnhuff.github.io
baseurl: ""

# Theme Config
remote_theme: sylhare/Type-on-Strap
title: Chris Huff
header_text: Working as intended
footer_text: Copyright 2024
description: Working as intended.
avatar: assets/img/avatar.png
color_theme: auto

# Blog
excerpt: true
post_navigation: true

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build settings
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]